[package]
name = "figment-cliarg-provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figment = "0.10.6"
wild = "2.0.4"
argmap = "1.1.2"